version: '3.8'
services:
  minio1:
    image: minio/minio:latest
    hostname: minio1
    volumes:
      - ${DMOD_OBJECT_STORE_HOST_DIR_1:?No host data directory 1 for object store storage provided}:/export1
      - ${DMOD_OBJECT_STORE_HOST_DIR_2:?No host data directory 2 for object store storage provided}:/export2
      #- minio1-data3:/export3
      #- minio1-data4:/export4
      #- minio1-data5:/export5
      #- minio1-data6:/export6
    expose:
      - 9000
    ports:
      - ${DMOD_OBJECT_STORE_1_HOST_PORT:-9002}:9000
      - ${DMOD_OBJECT_STORE_1_CONSOLE_HOST_PORT:-9001}:9001
    networks:
      - mpi-net
      - requests-net
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio1==true
    command: server --address :9000 http://minio{1...2}/export{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    secrets:
      - source: secret_key
        target: secret_key
      - source: access_key
        target: access_key
      - source: exec_user_passwd
        target: exec_user_passwd
      - source: exec_user_name
        target: exec_user_name
  minio2:
    image: minio/minio:latest
    hostname: minio2
    volumes:
      - ${DMOD_OBJECT_STORE_HOST_DIR_1:?No host data directory 1 for object store storage provided}:/export1
      - ${DMOD_OBJECT_STORE_HOST_DIR_2:?No host data directory 2 for object store storage provided}:/export2
      #- minio2-data3:/export3
      #- minio2-data4:/export4
      #- minio2-data5:/export5
      #- minio2-data6:/export6
    expose: 
      - 9000
    ports:
      - ${DMOD_OBJECT_STORE_2_HOST_PORT:-9004}:9000
      - ${DMOD_OBJECT_STORE_2_CONSOLE_HOST_PORT:-9003}:9001
    networks:
      - mpi-net
      - requests-net
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio2==true
    command: server --address :9000 http://minio{1...2}/export{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    secrets:
      - source: secret_key
        target: secret_key
      - source: access_key
        target: access_key
      - source: exec_user_passwd
        target: exec_user_passwd
      - source: exec_user_name
        target: exec_user_name

  minio_proxy:
    image: nginx:1.21.1-alpine
    hostname: minio_proxy
    networks:
        #- minio_distributed
        - requests-net
        - mpi-net
    volumes:
        - ${DMOD_OBJECT_STORE_PROXY_CONFIG:-./nginx.conf}:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
    #depends_on:
    #  - minio1
    #  - minio2
    deploy:
        restart_policy: 
            condition: on-failure
        placement:
            constraints:
                - node.labels.object_store_proxy==true
networks:
  mpi-net:
      external: true
      name: ${DOCKER_MPI_NET_NAME}
  requests-net:
      external: true
      name: ${DOCKER_REQUESTS_NET_NAME}
secrets:
  secret_key:
    file: ../secrets/object_store/secret_key
  access_key:
    file: ../secrets/object_store/access_key
  # Note that these need to be in environment, as other things also use them (or at least the values in the file)
  # However, our custom stack naming (i.e., with prefix) messes up just simply reusing the secret across stacks
  exec_user_passwd:
    file: ${DMOD_OBJECT_STORE_EXEC_USER_NAME_SECRET_FILE:?}
  exec_user_name:
    file: ${DMOD_OBJECT_STORE_EXEC_USER_PASSWD_SECRET_FILE:?}
