version: "3.7"

services:
  base:
    image: ${DOCKER_INTERNAL_REGISTRY_HOST?}:${DOCKER_INTERNAL_REGISTRY_PORT?}/nwm-base
    build: ./base
  deps:
      image: ${DOCKER_INTERNAL_REGISTRY_HOST?}:${DOCKER_INTERNAL_REGISTRY_PORT?}/nwm-deps:netcdf_${NETCDF_C_LIBRARY:-latest}
    build: ./nwm/deps
    depends_on:
      - base
  scheduler:
    image: ${DOCKER_INTERNAL_REGISTRY_HOST?}:${DOCKER_INTERNAL_REGISTRY_PORT?}/mpi-scheduler
    build: ./scheduler
    depends_on:
      - base
  nwm:
    image: ${DOCKER_INTERNAL_REGISTRY_HOST?}:${DOCKER_INTERNAL_REGISTRY_PORT?}/nwm-${NWM_NAME:-master}
    build:
      context: ./nwm
      args:
          REPO_URL: ${REPO_URL?}
          BRANCH: ${BRANCH?}
          COMMIT: ${COMMIT}
    #depends_on:
    #    - deps
    #For building, this only gives shared memory to each build step!!! shm_size: 2GB
networks:
  mpi-net:
    external: true
    name: ${DOCKER_MPI_NET_NAME}
