version: "3.7"

services:
  scheduler:
    image: ${DOCKER_INTERNAL_REGISTRY_HOST?}:${DOCKER_INTERNAL_REGISTRY_PORT}/mgmt
    networks:
      - ${DOCKER_MPI_NET_NAME}
    ports:
      - "22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_VOL_DOMAINS?}:/nwm/domains
      #- ${DOCKER_VOL_ANALYSIS_ASSIM}:/nwm/conus
      #- /apd_common/anthro/:/apd_common/anthro
    deploy:
      placement:
        constraints:
          - ${DOCKER_SCHEDULER_DEPLOY_CONSTRAINT_1:-node.role==manager}
          - ${DOCKER_SCHEDULER_DEPLOY_CONSTRAINT_2:-node.id!=notrealid_tautology_by_default}
  myredis:
    image: redis
    ports:
      - "6379"
    networks:
      - ${DOCKER_MPI_NET_NAME}
    entrypoint: ['redis-server', '/usr/local/etc/redis/redis.conf']
    #volumes:
    #  - /dev/shm:/dev/shm #Hack in shared memory filesystem
    deploy:
      placement:
        constraints:
          - ${DOCKER_MPIMASTER_DEPLOY_CONSTRAINT_1:--node.role==manager}
          - ${DOCKER_MPIMASTER_DEPLOY_CONSTRAINT_2:-node.id!=notrealid_tautology_by_default}

networks:
    mpi-net:
        external: true
        name: ${DOCKER_MPI_NET_NAME}
