version: "3"

services:
    registry:
        image: registry:2
        ports:
            - "${DOCKER_INTERNAL_REGISTRY_PORT}:${DOCKER_INTERNAL_REGISTRY_PORT}"
        volumes:
            # This must exist on manager node to provide a persistent store for images
            - ${DOCKER_HOST_IMAGE_STORE:-/opt/nwm_c/images}:/var/lib/registry
        networks:
            - ${DOCKER_MPI_NET_NAME}
        deploy:
            placement:
                constraints:
                    - ${DOCKER_REGISTRY_DEPLOY_CONSTRAINT:-node.role==manager}
networks:
    ${DOCKER_MPI_NET_NAME}:
        external: true
