version: "3.7"

services:
    #registry:
    #    image: registry
    #    networks:
    #        - mpi-net
    #    ports:
    #         - "5000"
    scheduler:
        # image: 127.0.0.1:5000/mpi-scheduler
        image: 127.0.0.1:5000/mgmt
        networks:
            - mpi-net
        #user: root
        # entrypoint: ['./entry.sh']
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /opt/nwm_c/domains:/nwm/domains
            - /apd_common/analysis_assim_extended:/nwm/conus 
        deploy:
            placement:
                constraints: [node.role == manager]
        #build: ./scheduler

    myredis:
        image: redis
        ports:
            - "6379"
        networks:
            - mpi-net
        entrypoint: ['redis-server', '/usr/local/etc/redis/redis.conf']
        volumes:
            - /apd_common/scui/nwm_service/scheduler/conf/redis.conf:/usr/local/etc/redis/redis.conf
        deploy:
            placement:
                constraints: [node.role == manager]
       
networks:
    mpi-net:
        external: true
