version: "3.7"

services:
  registry:
    image: registry:2
    ports:
      - "${DOCKER_INTERNAL_REGISTRY_PORT}:5000"
    volumes:
      # This must exist on manager node to provide a persistent store for images
      - ${DOCKER_HOST_IMAGE_STORE:-/opt/nwm_c/images}:/var/lib/registry
    networks:
      - ${DOCKER_MPI_NET_NAME}
    deploy:
      placement:
        constraints:
          - ${DOCKER_REGISTRY_DEPLOY_CONSTRAINT:-node.role==manager}
networks:
  mpi-net:
    external: true
    name: ${DOCKER_MPI_NET_NAME}
