version: "3"

# Declare all services that will be formed within their own containers
services:
  # Define a container belonging exclusively to nginx
  nginx:
    # Use the most barebones postgres instance
    image: nginx:1.16
    # Only restart if a failure occurs
    restart: on-failure
    # Forward everything hitting localhost on port 1337 to port 80 within the container
    ports:
      - ${DOCKER_GUI_NGINX_PORT:-8081}:80
    # Link everything within the static volume to /usr/wres-gui/static within the container -
    # this will help share resources
    volumes:
      - static_volume:/usr/maas_portal/static
      - ${DOCKER_GUI_NGINX_CONFIG_FILE:-./nginx/default.conf}:/etc/nginx/conf.d/default.conf
    # Make this container depend on the container holding the application server
    depends_on:
      - app_server
  # Define a container belonging exclusively to our django application
  app_server:
    image: python:3.7-alpine
    # Call this when starting the container
    entrypoint: /usr/maas_portal/entrypoint.sh
    command: gunicorn maas_experiment.wsgi:application --bind 0.0.0.0:8000
    # Only restart if a failure was encountered
    restart: on-failure
    #networks:
    #  - ${DOCKER_MPI_NET_NAME}
    # Run in debug mode and set all of the variables needed to connect to the postgres server on the internal network
    environment:
      - VENV_DIR=${DOCKER_GUI_CONTAINER_VENV_DIR:-}
      #- CERT_PATH # used by dispatch.py
      - PYTHONUNBUFFERED=1
      - MAAS_ENDPOINT=${DOCKER_GUI_MAAS_ENDPOINT:-http://localhost:${DOCKER_REQUESTS_HOST_PORT:-3012}}
      - MAAS_PORTAL_DEBUG=${DOCKER_GUI_MAAS_PORTAL_DEBUG:-true}
    volumes:
      - static_volume:/usr/maas_portal/static
      - .:/usr/maas_portal
    # Expose Django's port to the internal network so that nginx may access it
    expose:
      - 8000

# Define persistent volumes that may be shared and persisted between containers
volumes:
  static_volume: