# Generated by Django 3.1.7 on 2021-04-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the formulation', max_length=100)),
                ('description', models.TextField(help_text='What the formulation seeks to achieve')),
            ],
        ),
        migrations.CreateModel(
            name='FormulationParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the parameter for the formulation', max_length=50)),
                ('description', models.CharField(blank=True, help_text='How this parameter affects the formulation', max_length=200, null=True)),
                ('value_type', models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('date', 'Date'), ('datetime', 'Date and Time')], help_text='The type of the ', max_length=50)),
                ('minimum', models.FloatField(blank=True, help_text='The minimum possible numerical value for this parameter', null=True)),
                ('maximum', models.FloatField(blank=True, help_text='The maximum possible numerical value for this parameter', null=True)),
                ('default_value', models.CharField(blank=True, help_text='An optional default value for the parameter', max_length=50, null=True)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaaS.formulation')),
            ],
        ),
    ]
