# Generated by Django 3.1.7 on 2021-04-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaaS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulationparameter',
            name='group',
            field=models.CharField(blank=True, help_text='A sub-group to which this parameter belongs', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formulationparameter',
            name='is_list',
            field=models.BooleanField(default=False, help_text='Whether or not this variable should be a list'),
        ),
    ]
