version: "3.7"

services:
  py-sources:
    image: ${DOCKER_INTERNAL_REGISTRY_HOST?}:${DOCKER_INTERNAL_REGISTRY_PORT?}/nwmaas-py-sources
    build:
      context: ../../
      dockerfile: stacks/py_sources/py_source.Dockerfile
      args:
        comms_package_name: ${PYTHON_PACKAGE_DIST_NAME_COMMS:?}
        access_package_name: ${PYTHON_PACKAGE_DIST_NAME_ACCESS:?}
        externalrequests_package_name: ${PYTHON_PACKAGE_DIST_NAME_EXTERNAL_REQUESTS:?}
        request_service_package_name: ${PYTHON_PACKAGE_DIST_NAME_REQUEST_SERVICE:?}
        scheduler_package_dist_name: ${PYTHON_PACKAGE_DIST_NAME_SCHEDULER:?}
        scheduler_service_package_dist_name: ${PYTHON_PACKAGE_DIST_NAME_SCHEDULER_SERVICE:?}
