version: "3.7"

services:
    myredis:
        image: redis
#        networks:
#            - mpi-net
        #user: root
        entrypoint: ['redis-server', '/usr/local/etc/redis/redis.conf']
        volumes:
            - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - "6379:6379"
        deploy:
            placement:
                constraints: [node.role == manager]
       
#networks:
#    mpi-net:
#        external: true
